version: 3

updates:
  # NPM dependencies - security updates only
  - package-ecosystem: "npm"
    directory: "/"            
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "security"
      include: "scope"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "all"
        update-type: "security"   # Only security updates
    rebase-strategy: "auto"

  # GitHub Actions dependencies - security updates only  
  - package-ecosystem: "github-actions"
    directory: "/"                
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "security"
      include: "scope"
    open-pull-requests-limit: 0  
    allow:
      - dependency-type: "all"
        update-type: "security"   # Only security updates
    rebase-strategy: "auto"
