version: 2

updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"                # adjust if package.json is in a subdirectory
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"                # always root
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
